// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYhUbsr7bfZfoqYqPiQsRh4UfTWlAifaA',
    appId: '1:599047316506:web:c212ad9450e37d7e199da3',
    messagingSenderId: '599047316506',
    projectId: 'uts-aguskusuma1',
    authDomain: 'uts-aguskusuma1.firebaseapp.com',
    storageBucket: 'uts-aguskusuma1.firebasestorage.app',
    measurementId: 'G-LD9B922B55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-vWUK6kLEugPdsiG2mHF1td_XLvfJ00',
    appId: '1:599047316506:android:232eddd511bce631199da3',
    messagingSenderId: '599047316506',
    projectId: 'uts-aguskusuma1',
    storageBucket: 'uts-aguskusuma1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsvSZwzI0zPONvRmKu8ILIxjniXQ-Z574',
    appId: '1:599047316506:ios:15c8bef20e41e4b2199da3',
    messagingSenderId: '599047316506',
    projectId: 'uts-aguskusuma1',
    storageBucket: 'uts-aguskusuma1.firebasestorage.app',
    iosBundleId: 'com.example.dayaAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsvSZwzI0zPONvRmKu8ILIxjniXQ-Z574',
    appId: '1:599047316506:ios:15c8bef20e41e4b2199da3',
    messagingSenderId: '599047316506',
    projectId: 'uts-aguskusuma1',
    storageBucket: 'uts-aguskusuma1.firebasestorage.app',
    iosBundleId: 'com.example.dayaAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYhUbsr7bfZfoqYqPiQsRh4UfTWlAifaA',
    appId: '1:599047316506:web:b54b9cbe179e2582199da3',
    messagingSenderId: '599047316506',
    projectId: 'uts-aguskusuma1',
    authDomain: 'uts-aguskusuma1.firebaseapp.com',
    storageBucket: 'uts-aguskusuma1.firebasestorage.app',
    measurementId: 'G-7QK1CFWBGQ',
  );
}
